-- Schema Supabase para StakeBet v2.0
-- Rode este script no SQL Editor do Supabase após criar o projeto

-- ═══════════════════════════════════════════
-- TABELAS PRINCIPAIS
-- ═══════════════════════════════════════════

-- Apostas Simples
CREATE TABLE IF NOT EXISTS simples_bets (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  casa        TEXT NOT NULL,
  odd         DECIMAL(10,2) NOT NULL,
  aposta      DECIMAL(12,2) NOT NULL,
  retorno     DECIMAL(12,2) NOT NULL DEFAULT 0,
  tipo        TEXT NOT NULL CHECK (tipo IN ('green','red','live','cashout')),
  descricao   TEXT,
  desc_curta  TEXT,
  data_aposta TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_simples_user ON simples_bets(user_id);
CREATE INDEX idx_simples_data ON simples_bets(user_id, data_aposta DESC);

-- Surebets
CREATE TABLE IF NOT EXISTS surebet_ops (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  evento       TEXT,
  descricao    TEXT,
  data_fim     TIMESTAMPTZ,
  nota         TEXT,
  pernas       JSONB NOT NULL DEFAULT '[]',
  investimento DECIMAL(12,2) NOT NULL,
  lucro_min    DECIMAL(12,2) NOT NULL DEFAULT 0,
  tipo         TEXT NOT NULL DEFAULT 'live' CHECK (tipo IN ('green','red','live')),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_sure_user ON surebet_ops(user_id);

-- Duplo Green
CREATE TABLE IF NOT EXISTS dg_ops (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  evento       TEXT,
  descricao    TEXT,
  data_fim     TIMESTAMPTZ,
  nota         TEXT,
  pernas       JSONB NOT NULL DEFAULT '[]',
  investimento DECIMAL(12,2) NOT NULL,
  recebidos    JSONB DEFAULT '[]',
  comissoes    JSONB DEFAULT '[]',
  tipo         TEXT NOT NULL DEFAULT 'live' CHECK (tipo IN ('green','red','live')),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_dg_user ON dg_ops(user_id);

-- Configurações do usuário (bancas, metas, ciclos)
CREATE TABLE IF NOT EXISTS user_configs (
  user_id              UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  banca_simples        DECIMAL(12,2) NOT NULL DEFAULT 0,
  banca_sure           DECIMAL(12,2) NOT NULL DEFAULT 0,
  banca_dg             DECIMAL(12,2) NOT NULL DEFAULT 0,
  meta_simples         DECIMAL(12,2) NOT NULL DEFAULT 0,
  meta_sure            DECIMAL(12,2) NOT NULL DEFAULT 0,
  meta_dg              DECIMAL(12,2) NOT NULL DEFAULT 0,
  ciclo_inicio_simples TIMESTAMPTZ,
  ciclo_inicio_sure    TIMESTAMPTZ,
  ciclo_inicio_dg      TIMESTAMPTZ,
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Casas de aposta (bookmakers)
CREATE TABLE IF NOT EXISTS casas (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome    TEXT NOT NULL,
  UNIQUE(user_id, nome)
);
CREATE INDEX idx_casas_user ON casas(user_id);

-- Lixeira unificada
CREATE TABLE IF NOT EXISTS trash_items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  tipo          TEXT NOT NULL CHECK (tipo IN ('simples','sure','dg')),
  original_data JSONB NOT NULL,
  deleted_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_trash_user ON trash_items(user_id);

-- ═══════════════════════════════════════════
-- ROW-LEVEL SECURITY (RLS)
-- ═══════════════════════════════════════════

ALTER TABLE simples_bets ENABLE ROW LEVEL SECURITY;
ALTER TABLE surebet_ops ENABLE ROW LEVEL SECURITY;
ALTER TABLE dg_ops ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE casas ENABLE ROW LEVEL SECURITY;
ALTER TABLE trash_items ENABLE ROW LEVEL SECURITY;

-- Policies: usuário só vê os próprios dados
CREATE POLICY "Users can only access their own bets"
  ON simples_bets FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can only access their own surebets"
  ON surebet_ops FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can only access their own DG ops"
  ON dg_ops FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can only access their own configs"
  ON user_configs FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can only access their own casas"
  ON casas FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can only access their own trash"
  ON trash_items FOR ALL USING (auth.uid() = user_id);

-- ═══════════════════════════════════════════
-- TRIGGER: atualiza updated_at automaticamente
-- ═══════════════════════════════════════════
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_simples_updated_at BEFORE UPDATE ON simples_bets FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tg_sure_updated_at BEFORE UPDATE ON surebet_ops FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tg_dg_updated_at BEFORE UPDATE ON dg_ops FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER tg_config_updated_at BEFORE UPDATE ON user_configs FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ═══════════════════════════════════════════
-- REALTIME: habilita subscriptions
-- ═══════════════════════════════════════════
ALTER PUBLICATION supabase_realtime ADD TABLE simples_bets;
ALTER PUBLICATION supabase_realtime ADD TABLE surebet_ops;
ALTER PUBLICATION supabase_realtime ADD TABLE dg_ops;
ALTER PUBLICATION supabase_realtime ADD TABLE user_configs;
ALTER PUBLICATION supabase_realtime ADD TABLE casas;
ALTER PUBLICATION supabase_realtime ADD TABLE trash_items;
